import Head from "next/head";
import About from "../components/about.component";
import Contact from "../components/contact.component";
import Header from "../components/header.component";
import Main from "../components/main.component";
import Project from "../components/project.component";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Foluke Odusanya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

     
      </Head>
      <Header />
      <Main />
      <About />
      <Project />
      <Contact />
    </div>
  );
}
